/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package todoApp;

import java.sql.Connection;
import util.conexaodb;

public class App {
       

    public static void main(String[] args) {
        Connection c = conexaodb.getConnection();
        
        conexaodb.closeConnection(c);
    }
}
